### ISSUE TITLE
Button Field Type

### ISSUE THREAD

**Issue by pyrographics** [Mark-H/ClientConfig#100]
Thank you for this extra Mark! Took me too long to find it.  

I would like to request the feature of a button field type that will add a button to take the user to update a chunk or resource.  This way MODX can point the user to common tasks such as updating their footer code, contact information or social media links without having to dig for it.

**Comment by Mark-H** [comment]
Pointing the user away from ClientConfig to manage configuration is rather backwards. The idea is that ClientConfig holds your contact information and social media links, so they don't have to dig elsewhere. 

If you still need a button, use Quickstart Buttons to put a button on the dashboard.
