### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by m6246** [Mark-H/ClientConfig#106]
I just started playing with MODx today and was drawn to this extension as I thought it would enable for a simple and clean layout for clients to update the content on their website. However, after some reading it seems this extension is developed towards website developers to override stuff that their clients might use.

It seems that even with the comprehensive range of permissions, one cannot create a simple dashboard with just template variable fields and optionally the filemanager for uploading files. Looking at ClientConfig, it seems exactly what I'm after. If it could have a widget in edit mode, which could be put on the client dashboard, it would enable them to easily update content.

Now I guess I'm not far enough into MODx to know about different plugins that already do this, so if there are any please let me know. Also, I'm not sure if it is optimized for caching and such. Aside from that, maybe this could make for a nice feature request.

**Comment by Mark-H** [comment]
Hi @m6246 (nice avatar!),

Could you elaborate with what you're looking to create when you talk about a simple dashboard? 

ClientConfig is meant to provide clients a way to edit certain site-wide settings/configuration, without forcing them to use the system settings grid, which can be a bit of a pain ;)

**Comment by m6246** [comment]
Wow, that's fast ;) I want to create a minimal interface in which a client can update some data (textarea -> some div content, textfield -> some header) after logging in, but leaving out all other MODx sections, buttons, etc.

**Comment by Mark-H** [comment]
Hmm maybe you're just looking for template variables on a resource, and form customization to hide what you don't use? Or ContentBlocks, though that sounds more advanced than what you're looking for. 

The clientconfig.admin_groups setting determines who can see the admin button in the component. If it's not showing in the top menu, the user might not have the components/extras (don't recall what it's called) permission, but that's not specific to ClientConfig and would just hide the entire Extras nav item.

**Comment by m6246** [comment]
Hi Mark,

thanks, enabling the components permission did the trick. Having the Media + ClientConfig menu items and hiding everything else will do for now. Form customization sounds like the better solution but apparently I'm still to learn a lot about MODx.

thanks for your support and efforts

**Comment by Eleiz11** [comment]
First time using clientconfig and working like a charm. I am trying to get a widget on the dashboard so clients don't go snooping or editing things they don't need be. There is a video by Dash that has that ability, and it looks super easy for clients to use.

**Comment by Mark-H** [comment]
Are you looking for something like Quickstart Buttons?

**Comment by Eleiz11** [comment]
Actually yes. Suppose I wasn't wording it correctly. I am learning so much
super quickly with MODX (so much love).
