### ISSUE TITLE
Content not included in search results

### ISSUE THREAD

**Issue by tassu** [Mark-H/ClientConfig#107]
My client have timetables that I made in clientconfig. Output is ok, timetables show as they should in site. But when I try to search (simplesearch extra) none of content by clientconfig is included in search results.

Simplesearch documentation says that it not support TV content. Is that the reason?

Edit: Tried AdvSearch too, no results in search those contents that ClientConfig renders.

**Comment by Mark-H** [comment]
ClientConfig stores its data in custom tables. If you want to search through those, you'll need to write something that searches that custom table. 

I think advSearch may have some options to make that easier, where you can join certain custom tables, but as ClientConfig doesn't have a relation to resources that might be tricky.
