### ISSUE TITLE
Dashboard Widget

### ISSUE THREAD

**Issue by crecorn** [Mark-H/ClientConfig#108]
This isn't an issue, but how could I have these show on a dashboard?

**Comment by Mark-H** [comment]
What exactly would you like to show on a dashboard?

**Comment by crecorn** [comment]
I set up a news crawl that a client updates regularly. I'd like to set this up so the client just logs in and it's on the dashboard.

**Comment by greyskymedia** [comment]
Why not simply create a regular custom dashboard widget?

**Comment by Mark-H** [comment]
You could use [Quickstart Buttons](https://www.modmore.com/extras/quickstartbuttons/) to add a button on the dashboard that points to the configuration CMP.
