### ISSUE TITLE
OnHandleRequest vs. OnMODXInit

### ISSUE THREAD

**Issue by enminc** [Mark-H/ClientConfig#109]
It may be that CC predates the Sys Event "OnMODXInit". Wondering if you might consider changing to this event so that CC can be used for MODX_API_MODE mode as well as external loading of modx where a request is not being used.

I have added this event to the plugin on several of my sites but it will be overwritten should there ever be an update of CC.

**Comment by greyskymedia** [comment]
Just curious, what are you using API Mode for?

**Comment by Mark-H** [comment]
Yep, don't think OnMODXInit was around when ClientConfig was first developed in... 2012?

Will need to look into when it was added specifically, but if that's not too recent I don't see a problem changing it in ClientConfig.

**Comment by enminc** [comment]
@greyskymedia 

My use fits more into the external loading category. I have a few accounts where MODX is simply a CMF for a remote non-MODX site or running batch and test scripts that may load modx externally to run a snippet that may depend on System Settings within that should be over loaded with the CC Settings.

**Comment by enminc** [comment]
Thanks Mark. Ya give it a review. I see nothing in the way myself. There are only a "few lines" apart in where they are triggered. 

pretty much the last thing ->initialize() does is invoke 'OnMODXInit' then calls handler and then handler calls OnHandleRequest

**Comment by sebastian-marinescu** [comment]
I think #115 will take care of this.
