### ISSUE TITLE
ClientConfig not saving

### ISSUE THREAD

**Issue by jcamachott** [Mark-H/ClientConfig#111]
Any ideas on this? Cannot save anything. A small "Saving.." box shows up and stays there indefinitely. This is what shows up in chrome dev tools:

![image](https://cloud.githubusercontent.com/assets/1188776/13862385/59270a06-ec69-11e5-875f-f3eeea5a2654.png)

Thanks in advance.

**Comment by Mark-H** [comment]
That 403 sounds like a file permission or mod security issue... The js error is probably a result of the failed Ajax request

**Comment by jcamachott** [comment]
Thanks, it was indeed mod_security...odd that I was able to make changes a few days ago though.
