### ISSUE TITLE
How change RTE?

### ISSUE THREAD

**Issue by edDimensi** [Mark-H/ClientConfig#113]
I want to change RTE editor from MCE to TinyMce RTE? Thx for anwser. Sorry for english

**Comment by Mark-H** [comment]
ClientConfig loads whatever editor you have installed and configured in the which_editor setting.

**Comment by edDimensi** [comment]
![default](https://cloud.githubusercontent.com/assets/11390039/14026637/d64b4a42-f204-11e5-8a1a-34e18e0495f7.jpg)

Then CC not work with tinymce rte...(

**Comment by Mark-H** [comment]
That looks like an error coming from TinyMCE RTE itself... if this still happens on the latest version, please open an issue in their repo (cross link it here if you can).
