### ISSUE TITLE
Required numberfield can't be set to 0

### ISSUE THREAD

**Issue by Lefthandmedia** [Mark-H/ClientConfig#119]
### Summary
A Numberfield won't save if the value has been set to 0. This seems to be related to the 'Setting is required' setting

### Step to reproduce
create a setting in admin mode. choose fieldtype 'Number' and 'setting is required'. Go to client mode, Fill out any number and it will save. but when you change the number to 0 it won't save.

### Expected behavior
I would expect the number to be saved. An TV with input 'Number' CAN be saved to 0. Number is not an input type one can choose for system_setting

### Environment
ClientConfig version, MODX version, Operating System, MySQL version, PHP version, etc.
CC 1.3.2, modx 2.5.2PL

**Comment by Mark-H** [comment]
Thanks for the report, is fixed in 1.4.
