### ISSUE TITLE
No setting output for site start page 

### ISSUE THREAD

**Issue by hitodev** [Mark-H/ClientConfig#120]
### Summary

Strange thing:
[[++aConfigSetting]] doesn't work on context start site page (site_start).

### Step to reproduce
1/ place a setting placeholder in site_start page resource [[++aConfigSetting]] 
2/ change start page and refresh cache

### Observed behavior
1/ No output for setting
2/ Work as expected

### Expected behavior
Setting output

### Environment
lientconfig-1.3.2-pl
MODX Revolution 2.5.2-pl

**Comment by Mark-H** [comment]
This seems to work fine here. Any chance this may have been a cache issue, where refreshing the cache, and not changing the site_start resource fixed it?
