### ISSUE TITLE
Set alternative RTE

### ISSUE THREAD

**Issue by DonQuicky** [Mark-H/ClientConfig#122]
### Summary
When choosing RTE as fieldtype a minimal version of TinyMCE is used. I use TinyMCE Rich Text Editor as editor and I want to use this one as RTE in ClientConfig.

### Step to reproduce
Each time when using RTE

### Observed behavior
Minimal TinyMCE is being used

### Expected behavior
Default RTE set in settings should be respected

### Environment
ClientConfig 1.3.2-pl, TinyMCE Rich Text Editor 1.1.1-pl, MODX 2.5.2-pl

**Comment by Mark-H** [comment]
ClientConfig uses the MODx.loadRTE method for RTEs, so that's supposed to work just fine?

**Comment by DonQuicky** [comment]
I expected that also, but two different RTE's are shows. See screenshots.

RTE in content editor of resource:

![2017-01-31 20_43_10-bewerken_ home _ modx revolution - opera](https://cloud.githubusercontent.com/assets/1911772/22481728/8cf594b8-e7f6-11e6-8b48-89a1319ad0dd.png)

RTE in field RTE of ClientConfig:

![2017-01-31 20_43_59-configuratie _ modx revolution - opera](https://cloud.githubusercontent.com/assets/1911772/22481786/c37e6b5e-e7f6-11e6-8591-1b757ba488f9.png)

The extra TinyMCE Rich Text Editor I use is the only one installed and set as default RTE in the system settings.

What I miss in the RTE offered in field of ClientConfig is the option of inserting a link or image. Also the option to show the source code of content I do miss.

**Comment by Mark-H** [comment]
Gotcha. Bug found and fixed. Release will be coming out today or tomorrow via modmore.com.
