### ISSUE TITLE
Facility to set media source for image input

### ISSUE THREAD

**Issue by vierkantemeter** [Mark-H/ClientConfig#66]
Title says all ;) Facility to set media source for image input. Or at least respect default_media_source

**Comment by crimsonpixel** [comment]
Being able to select mediasource for images in clientconfig would be useful especially where allowing users to upload a company logo or similar. Restricts problems with uploading image into wrong folder etc etc.

**Comment by labr1005** [comment]
Dirty quick fix:

ClientConfig 1.3.1-pl
assets/components/clientconfig/js/mgr/sections/home.js
line 101
add ```field.source = X;```
where ```X ``` is the ID of the media source.
```
if (field.xtype == 'modx-panel-tv-image') {
    field.tv = value.key;
    field.source = 2;
    field.relativeValue = (value.value != '') ? value.value : value.default;
}
```

**Comment by pepebe** [comment]
+1 for setting a default media source. 

Last week I had a client deleting .htaccess, index.php and core.config.php because "they they looked ugly". 

Yes we can restrict a lot of stuff in user ACL, but I learned that hard way that users find ways to cause havoc,

**Comment by rainbowtiger** [comment]
Yes, we need to be able to pick the media source for images. Just obeying the default media source won't always work. I have that set to the documents folder in my websites, because that's what people most often link to when using the link tool while editing.

**Comment by Mark-H** [comment]
1.3.2 introduced setting it to the default media source, 1.4 introduces the ability to set it per field specifically.
