### ISSUE TITLE
Feature Request: Add system event to track config changes

### ISSUE THREAD

**Issue by exside** [Mark-H/ClientConfig#83]
With the nice capabilities of setting in-runtime settings and probably many devs using client config for theme customization purposes I had the idea (within another extra I'm working on) to make a primitive css preprocessor that basically parses modx tags in normal .css files. The thought behind this is to have the advantage of variables, especially for colors, without having to use a real pre-processor (as I still like writing clean css by hand most).

The next step was to configure a few color system settings via client config and then replace them in the css on runtime (caching the result, no worries =D)...but exactly with the caching this thing is getting problematic because there seems to be no way of getting noticed when a config change happens and the css should be recompiled.

So I guess a quite simple solution would be a custom system event, something like OnConfigChange that is registered when ClientConfig is installed and then triggered via $modx->invokeEvent() at the right places in the save/update processors.

Does that make any sense?

**Comment by atorockio** [comment]
Hi, this would be a great feature to tie in with [cssSweet](https://github.com/sepiariver/cssSweet) which is "a suite of tools for processing (S)CSS" If there was a way for the css files that cssSweet creates to automatically update when client config settings are updated it would be very helpful.

Has anyone worked on anything like this or could someone point me in the right direction to get started on creating a system event like "OnConfigChange"? Is it doable?

Thanks!

**Comment by sepiariver** [comment]
+1 on this please. I would indeed add support in https://github.com/sepiariver/cssSweet if ClientConfig invoked a custom event.

Maybe I'll try a PR—I know you're super busy Mark ;)

**Comment by Mark-H** [comment]
Yeah this would be a great addition. Wouldn't be too hard to add (just adding a call to $modx->fireEvent or what's the name of that again, in the settings/save processor).

**Comment by Daruse93** [comment]
Mark, really miss this functionality

**Comment by Mark-H** [comment]
Pull requests are welcome and one of the best ways to get something you want ;)

**Comment by Daruse93** [comment]
Mark, I added a pull-request

**Comment by Mark-H** [comment]
This was implemented per #117
