### ISSUE TITLE
Duplicate column name 'sortorder' on install

### ISSUE THREAD

**Issue by degoya** [Mark-H/ClientConfig#90]
when i install ClientConfig 1.3.1 on modx 2.3.2 and installed redactor and contentblock before client config i get the following error.

	Error adding field cgSetting->sortorder: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'sortorder' )
	Error adding field cgGroup->sortorder: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'sortorder' ) 

Btw. i've installed modx from cli. and Client Config as local package.

this error shows up every install i've tested.

**Comment by Mark-H** [comment]
That's safe to ignore, it just means fields it's trying to add as part of the update process already exist.
