### ISSUE TITLE
@SELECT in SelectLists, etc.

### ISSUE THREAD

**Issue by pepebe** [Mark-H/ClientConfig#93]
This is related to https://github.com/Mark-H/ClientConfig/issues/61

I believe it would be much more versatile if we could use @SELECT bindings inside the option field.

I guess this takes a controller, but it would be worth it.

**Comment by Mark-H** [comment]
`@SELECT` is too prone to abuse, so I wont support that. Chunks or snippets per #104 however would be a welcome addition.
