### ISSUE TITLE
Admin - Settings & Group Table to be able to edit inline

### ISSUE THREAD

**Issue by sturple** [Mark-H/ClientConfig#94]
The ability to edit inline select fields on the table as oppose to opening a new window (Quick edits)

**Comment by sebastian-marinescu** [comment]
Would inline-editing the _key, label and sortorder_ fields be sufficient in your opinion?

**Comment by Mark-H** [comment]
Would be nice to perhaps also have the group inline editable, as that would make organising things a lot quicker.

**Comment by sebastian-marinescu** [comment]
I also thought about it. But I haven't figured out yet, how to present a nice dropdown with the available values. Maybe just setting the xtype from here: https://github.com/Mark-H/ClientConfig/blob/master/assets/components/clientconfig/js/mgr/widgets/window.settings.js#L42

**Comment by sebastian-marinescu** [comment]
Done.
