### ISSUE TITLE
Admin - Sort Order on Settings and Groups Table

### ISSUE THREAD

**Issue by sturple** [Mark-H/ClientConfig#95]
To Show the sort orders on the admin table, and the ability to inline edit these fields in the table

**Comment by frogabog** [comment]
Feature Request - how about drag and drop for sort order (plus show it in the grid)

**Comment by sebastian-marinescu** [comment]
I added the sort-order as column. But I'm not sure how to implement the inline-edit or the drag-capability.

**Comment by sebastian-marinescu** [comment]
Could this be fixed in **1.3.3**? Also #94 could then be closed.
