### ISSUE TITLE
Also show the setting key in the client view

### ISSUE THREAD

**Issue by sottwell** [Mark-H/ClientConfig#96]
In the client view, the label and the description are displayed. It would be nice if it also displayed the key so the client would know what key to use. I dug through the files, but couldn't find where the actual client grid display is defined. Yes, I know the hover tooltip displays the proper tag, but you can't copy/paste those.

**Comment by Mark-H** [comment]
If you're going to ask the client to use the tags, I think the easiest solution is to add the tag to the field description. That will show up under the field.
