### ISSUE TITLE
Can't save richtext content with tinymce-rte

### ISSUE THREAD

**Issue by pawelmil** [Mark-H/ClientConfig#97]
Hi, content can't be saved when using tinymce-rte in ClientConfig.

**Comment by Mark-H** [comment]
I think this is an issue with tinymce-rte, that's happened with other extras too.

**Comment by pawelmil** [comment]
Hi, I wrote an issue in tinymce-rte, but they said: you need to write 
bug to https://github.com/Mark-H/ClientConfig
Tinymce-rte Issue:
https://github.com/modxcms/tinymce-rte/issues/17#issuecomment-106593228

W dniu 2015-07-01 o 16:04, Mark Hamstra pisze:
>
> I think this is an issue with tinymce-rte, that's happened with other 
> extras too.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Mark-H/ClientConfig/issues/97#issuecomment-117686268>.
>

-- 

Z poważaniem,
Paweł Milewski

<https://pvi.pl/>

AKTIZ Paweł Milewski
ul. Wspólna 5, 18-200 Wysokie Mazowieckie
NIP 722 131 83 13
e-mail: biuro@pvi.pl
tel. 86 270 98 81
www.pvi.pl <https://pvi.pl/>

**Comment by Jako** [comment]
CKEditor seems to have an issue too with ClientConfig.

**Comment by Mark-H** [comment]
Yes #102 is similar. These editors need to properly update the underlying textareas. ClientConfig doesn't immediately know which editor is used, so it also can't contain editor-specific logic to update that.

**Comment by Mark-H** [comment]
This should've been fixed in tinymce rte as I recall it being fixed for ContentBlocks as well.
